In [1]:
import pandas as pd

In [3]:
df = pd.read_csv('C:\\Users\\INFINIX\\Vistara-Innoverse\\ml\\recommendation\\properties.csv')
df.head()

,property_id,property_name,city,property_type,max_guests,bedrooms,beds,bathrooms,living_room,kitchen,...,free_cancellation,allows_pets,smoke_alarm,carbon_monoxide_alarm,step_free_access,accessible_parking,wide_guest_entry,step_free_bedroom,step_free_bathroom,host_languages
0,VST001,Urban Comfort Home 001,Delhi,Entire Home,6,4,5,2,1,1,...,1,0,1,1,0,0,0,0,0,"English,Hindi"
1,VST002,Green Garden Home 002,Mumbai,Apartment,6,3,5,2,1,1,...,1,0,1,1,0,0,0,0,0,"English,Hindi,Bengali"
2,VST003,City View Home 003,Bengaluru,Villa,3,2,2,1,1,1,...,1,0,1,1,0,0,0,0,0,"English,Hindi,Marathi"
3,VST004,Family Stay Home 004,Jaipur,Homestay,3,1,2,1,1,1,...,1,0,1,1,0,0,0,0,0,"English,Hindi,Tamil"
4,VST005,Lake View Home 005,Goa,Studio,7,4,6,2,0,0,...,0,0,1,1,0,0,0,0,0,"English,Hindi,Telugu"

In [4]:
verification_columns = ['property_id','property_name','verified','smoke_alarm','carbon_monoxide_alarm']
df[verification_columns].head(10)

,property_id,property_name,verified,smoke_alarm,carbon_monoxide_alarm
0,VST001,Urban Comfort Home 001,1,1,1
1,VST002,Green Garden Home 002,1,1,1
2,VST003,City View Home 003,1,1,1
3,VST004,Family Stay Home 004,1,1,1
4,VST005,Lake View Home 005,1,1,1
5,VST006,Modern Retreat Home 006,1,1,1
6,VST007,Cozy Corner Home 007,1,1,1
7,VST008,Heritage Home Home 008,0,1,1
8,VST009,Premium Residence Home 009,1,1,1
9,VST010,Hill View Home 010,1,1,1

In [7]:
def verification_score(property):
    score = 0

    #For Smoke Alarm Score
    if property['smoke_alarm'] == 1:
        score += 0.30

    #For Carbon Monoxide Alarm
    if property['carbon_monoxide_alarm'] == 1:
        score += 0.30

    #For Verified Score
    if property['verified'] ==1:
        score += 0.40

    return score

In [9]:
df['verification_score'] = df.apply(verification_score, axis = 1)

df[['property_id', 'property_name', 'verified', 'verification_score']]

   property_id                property_name  verified  verification_score
0       VST001       Urban Comfort Home 001         1                 1.0
1       VST002        Green Garden Home 002         1                 1.0
2       VST003           City View Home 003         1                 1.0
3       VST004         Family Stay Home 004         1                 1.0
4       VST005           Lake View Home 005         1                 1.0
..         ...                          ...       ...                 ...
95      VST096     Modern Retreat Haven 096         0                 0.6
96      VST097        Cozy Corner Haven 097         1                 1.0
97      VST098      Heritage Home Haven 098         1                 1.0
98      VST099  Premium Residence Haven 099         1                 1.0
99      VST100          Hill View Haven 100         1                 1.0

[100 rows x 4 columns]

In [10]:
def verification_status(score):
    if score >= 0.8:
        return 'Verified'
    elif score >= 0.5:
        return 'Needs  Review'
    else:
        return 'Rejected'

In [13]:
df["verification_status"] = df["verification_score"].apply(verification_status)

df[["property_id", "property_name","verification_score", "verification_status"]].head(10)

,property_id,property_name,verification_score,verification_status
0,VST001,Urban Comfort Home 001,1.0,Verified
1,VST002,Green Garden Home 002,1.0,Verified
2,VST003,City View Home 003,1.0,Verified
3,VST004,Family Stay Home 004,1.0,Verified
4,VST005,Lake View Home 005,1.0,Verified
5,VST006,Modern Retreat Home 006,1.0,Verified
6,VST007,Cozy Corner Home 007,1.0,Verified
7,VST008,Heritage Home Home 008,0.6,Needs Review
8,VST009,Premium Residence Home 009,1.0,Verified
9,VST010,Hill View Home 010,1.0,Verified

In [14]:
df["verification_status"].value_counts()

verification_status
Verified         78
Needs  Review    22
Name: count, dtype: int64

In [16]:
df[["property_id","property_name","verification_score","verification_status"]].head(10)

,property_id,property_name,verification_score,verification_status
0,VST001,Urban Comfort Home 001,1.0,Verified
1,VST002,Green Garden Home 002,1.0,Verified
2,VST003,City View Home 003,1.0,Verified
3,VST004,Family Stay Home 004,1.0,Verified
4,VST005,Lake View Home 005,1.0,Verified
5,VST006,Modern Retreat Home 006,1.0,Verified
6,VST007,Cozy Corner Home 007,1.0,Verified
7,VST008,Heritage Home Home 008,0.6,Needs Review
8,VST009,Premium Residence Home 009,1.0,Verified
9,VST010,Hill View Home 010,1.0,Verified

In [34]:
def verification_reasons(property):
    reasons = []

    if property["verified"] == 1:
        reasons.append("Property information verified")

    if property["smoke_alarm"] == 1:
        reasons.append("Smoke alarm available")

    if property["carbon_monoxide_alarm"] == 1:
        reasons.append("Carbon monoxide alarm available")

    if property["verified"] == 0:
        reasons.append("Property verification not completed")

    if property["smoke_alarm"] == 0:
        reasons.append("Smoke alarm not confirmed")

    if property["carbon_monoxide_alarm"] == 0:
        reasons.append("Carbon monoxide alarm not confirmed")

    return reasons

In [35]:
top_property = df.iloc[0]

verification_reasons(top_property)

['Property information verified',
 'Smoke alarm available',
 'Carbon monoxide alarm available']

In [36]:
df["verification_status"] = df["verification_score"].apply(verification_status)

In [37]:
df[["property_id","property_name","verification_score","verification_status"]].head(10)

,property_id,property_name,verification_score,verification_status
0,VST001,Urban Comfort Home 001,1.0,Verified
1,VST002,Green Garden Home 002,1.0,Verified
2,VST003,City View Home 003,1.0,Verified
3,VST004,Family Stay Home 004,1.0,Verified
4,VST005,Lake View Home 005,1.0,Verified
5,VST006,Modern Retreat Home 006,1.0,Verified
6,VST007,Cozy Corner Home 007,1.0,Verified
7,VST008,Heritage Home Home 008,0.6,Needs Review
8,VST009,Premium Residence Home 009,1.0,Verified
9,VST010,Hill View Home 010,1.0,Verified

In [38]:
df["verification_status"].value_counts()

verification_status
Verified         78
Needs  Review    22
Name: count, dtype: int64

In [39]:
property = df.iloc[0]

print("Property:", property["property_name"])
print("Score:", property["verification_score"])
print("Status:", property["verification_status"])

Property: Urban Comfort Home 001
Score: 1.0
Status: Verified

In [40]:
review_property = df[df["verification_status"] == "Needs  Review"].iloc[0]

print(review_property["property_name"])
print(review_property["verification_score"])
print(review_property["verification_status"])

Heritage Home Home 008
0.6
Needs  Review

In [41]:
review_reasons = verification_reasons(review_property)

print("Property:", review_property["property_name"])
print("Reasons:")
for reason in review_reasons:
    print("✓", reason)

Property: Heritage Home Home 008
Reasons:
✓ Smoke alarm available
✓ Carbon monoxide alarm available
✓ Property verification not completed

In [42]:
print("Verification Score:", round(review_property["verification_score"] * 100, 2), "/ 100")
print("Status:", review_property["verification_status"])

Verification Score: 60.0 / 100
Status: Needs  Review

In [43]:
df.to_csv("properties_with_verification.csv", index=False)